/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import classes.Product;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.Image;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.Plot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Kaviraj
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form nav_bar
     */
    Connection conn = dbConnection.dbConnector();
    int wholesalerid;

    public Dashboard(int sessionid) {

        //id as session
        wholesalerid = sessionid;

        initComponents();
        jScrollPane1.setPreferredSize(new Dimension(750, 400));

        ImageIcon frameicon = new ImageIcon(this.getClass().getResource("/Resources/Images/shop.png"));
        this.setIconImage(frameicon.getImage());

        PreparedStatement stm = null;
        ResultSet rs = null;
        try {
            String query = "SELECT id FROM invoice WHERE wholesaler_id = ?";
            stm = conn.prepareStatement(query);
            stm.setInt(1, wholesalerid);

            rs = stm.executeQuery();

            GridBagConstraints c = new GridBagConstraints();
            c.gridx = 0;
            c.gridy = 1;
            c.weightx = 1;
            c.weighty = 1;

            int count = 0;
            while (rs.next()) {
                String id = rs.getString("id");
                //creating the button invoice
                count++;
                JButton b = new JButton("Invoice " + count);

                //properties of the button
                b.setPreferredSize(new Dimension(150, 60));
                b.setFont(new Font("Arial", Font.PLAIN, 20));

                //Listener for the button
                b.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        bMouseClicked(id);
                    }
                });
                //This will increase the y coordinates for the button
                c.gridy++;
                //adding button with constraints c
                invoicePanel.add(b, c);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

        //Set title of frame
        setTitle("Dashboard");
        //The following set the frame to launch in maximised mode
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    public void bMouseClicked(String id) {
        PreparedStatement det = null;
        ResultSet rs = null;
        int btnid = Integer.parseInt(id);
        String query = "SELECT invoice.id, users.cname, product.name, invoice.quantity, invoice.date_added, invoice.delivered FROM invoice, product , users WHERE invoice.id = ? AND invoice.supermarket_id = users.id AND invoice.product_id = product.id";

        try {
            det = conn.prepareStatement(query);
            det.setInt(1, btnid);

            rs = det.executeQuery();

            tbl.setModel(DbUtils.resultSetToTableModel(rs));
            tbl.setFont(new Font("Serif", Font.BOLD, 20));
            tbl.setForeground(Color.WHITE);

            tbl.setDefaultEditor(Object.class, null);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error !");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        invoiceBigBtn = new javax.swing.JPanel();
        invoiceIco = new javax.swing.JLabel();
        lblInvoice = new javax.swing.JLabel();
        statsBigBtn = new javax.swing.JPanel();
        statsIco = new javax.swing.JLabel();
        lblStats = new javax.swing.JLabel();
        addBigBtn = new javax.swing.JPanel();
        addIco = new javax.swing.JLabel();
        lblAdd = new javax.swing.JLabel();
        reportBigBtn = new javax.swing.JPanel();
        reportIco = new javax.swing.JLabel();
        lblReport = new javax.swing.JLabel();
        logpanel1 = new javax.swing.JPanel();
        outIco = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        invoicePanel = new javax.swing.JPanel();
        invoiceTitle = new javax.swing.JLabel();
        lblList = new javax.swing.JLabel();
        lblDetails = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        morePanel = new javax.swing.JPanel();
        SaveBtn = new javax.swing.JButton();
        delCheck = new javax.swing.JCheckBox();
        statsPanel = new javax.swing.JPanel();
        statsTitle = new javax.swing.JLabel();
        chartPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        btnStockIn = new javax.swing.JButton();
        btnCat = new javax.swing.JButton();
        btnSales = new javax.swing.JButton();
        addPanel = new javax.swing.JPanel();
        lblAddNew = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblDesc = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        lblCat = new javax.swing.JLabel();
        txtCat = new javax.swing.JTextField();
        lblBP = new javax.swing.JLabel();
        txtBP = new javax.swing.JTextField();
        lblSP = new javax.swing.JLabel();
        txtSP = new javax.swing.JTextField();
        lblUrl = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        resetBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        lblQty = new javax.swing.JLabel();
        qtySpin = new javax.swing.JSpinner();
        imgPreviewer = new javax.swing.JPanel();
        previewerBtn = new javax.swing.JButton();
        reportPanel = new javax.swing.JPanel();
        reportTitle = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        reportArea = new javax.swing.JTextArea();
        saveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(95, 79, 205));

        jPanel1.setBackground(new java.awt.Color(95, 79, 205));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
        );

        invoiceBigBtn.setBackground(new java.awt.Color(156, 153, 230));
        invoiceBigBtn.setPreferredSize(new java.awt.Dimension(125, 45));
        invoiceBigBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invoiceBigBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                invoiceBigBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                invoiceBigBtnMouseExited(evt);
            }
        });

        lblInvoice.setBackground(new java.awt.Color(156, 153, 230));
        lblInvoice.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblInvoice.setForeground(new java.awt.Color(255, 255, 255));
        lblInvoice.setText("INVOICES");

        javax.swing.GroupLayout invoiceBigBtnLayout = new javax.swing.GroupLayout(invoiceBigBtn);
        invoiceBigBtn.setLayout(invoiceBigBtnLayout);
        invoiceBigBtnLayout.setHorizontalGroup(
            invoiceBigBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoiceBigBtnLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(invoiceIco)
                .addGap(29, 29, 29)
                .addComponent(lblInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        invoiceBigBtnLayout.setVerticalGroup(
            invoiceBigBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(invoiceIco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Image img1 = new ImageIcon(this.getClass().getResource("/Resources/Images/invoiceicon.png")).getImage();
        invoiceIco.setIcon(new ImageIcon(img1));

        statsBigBtn.setBackground(new java.awt.Color(156, 153, 230));
        statsBigBtn.setPreferredSize(new java.awt.Dimension(125, 45));
        statsBigBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statsBigBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                statsBigBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                statsBigBtnMouseExited(evt);
            }
        });

        lblStats.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblStats.setForeground(new java.awt.Color(255, 255, 255));
        lblStats.setText("STATISTICS");

        javax.swing.GroupLayout statsBigBtnLayout = new javax.swing.GroupLayout(statsBigBtn);
        statsBigBtn.setLayout(statsBigBtnLayout);
        statsBigBtnLayout.setHorizontalGroup(
            statsBigBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsBigBtnLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(statsIco)
                .addGap(30, 30, 30)
                .addComponent(lblStats)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        statsBigBtnLayout.setVerticalGroup(
            statsBigBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statsIco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblStats, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Image img4 = new ImageIcon(this.getClass().getResource("/Resources/Images/statsicon.png")).getImage();
        statsIco.setIcon(new ImageIcon(img4));

        addBigBtn.setBackground(new java.awt.Color(156, 153, 230));
        addBigBtn.setPreferredSize(new java.awt.Dimension(125, 45));
        addBigBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBigBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addBigBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addBigBtnMouseExited(evt);
            }
        });

        lblAdd.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblAdd.setForeground(new java.awt.Color(255, 255, 255));
        lblAdd.setText("ADD PRODUCT");

        javax.swing.GroupLayout addBigBtnLayout = new javax.swing.GroupLayout(addBigBtn);
        addBigBtn.setLayout(addBigBtnLayout);
        addBigBtnLayout.setHorizontalGroup(
            addBigBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addBigBtnLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(addIco)
                .addGap(28, 28, 28)
                .addComponent(lblAdd)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        addBigBtnLayout.setVerticalGroup(
            addBigBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addIco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Image img = new ImageIcon(this.getClass().getResource("/Resources/Images/addicon.png")).getImage();
        addIco.setIcon(new ImageIcon(img));

        reportBigBtn.setBackground(new java.awt.Color(156, 153, 230));
        reportBigBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportBigBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportBigBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportBigBtnMouseExited(evt);
            }
        });

        lblReport.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblReport.setForeground(new java.awt.Color(255, 255, 255));
        lblReport.setText("REPORT");

        javax.swing.GroupLayout reportBigBtnLayout = new javax.swing.GroupLayout(reportBigBtn);
        reportBigBtn.setLayout(reportBigBtnLayout);
        reportBigBtnLayout.setHorizontalGroup(
            reportBigBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportBigBtnLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(reportIco)
                .addGap(27, 27, 27)
                .addComponent(lblReport, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        reportBigBtnLayout.setVerticalGroup(
            reportBigBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reportIco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(reportBigBtnLayout.createSequentialGroup()
                .addComponent(lblReport, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Image img3 = new ImageIcon(this.getClass().getResource("/Resources/Images/reporticon.png")).getImage();
        reportIco.setIcon(new ImageIcon(img3));

        logpanel1.setBackground(new java.awt.Color(156, 153, 230));
        logpanel1.setRequestFocusEnabled(false);
        logpanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logpanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logpanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logpanel1MouseExited(evt);
            }
        });

        lblLogout.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.setText("LOGOUT");

        javax.swing.GroupLayout logpanel1Layout = new javax.swing.GroupLayout(logpanel1);
        logpanel1.setLayout(logpanel1Layout);
        logpanel1Layout.setHorizontalGroup(
            logpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logpanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(outIco)
                .addGap(27, 27, 27)
                .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logpanel1Layout.setVerticalGroup(
            logpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(outIco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(logpanel1Layout.createSequentialGroup()
                .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Image img2 = new ImageIcon(this.getClass().getResource("/Resources/Images/outicon.png")).getImage();
        outIco.setIcon(new ImageIcon(img2));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(statsBigBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(addBigBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(reportBigBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(invoiceBigBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invoiceBigBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addGap(51, 51, 51)
                .addComponent(statsBigBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addGap(48, 48, 48)
                .addComponent(addBigBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addGap(54, 54, 54)
                .addComponent(reportBigBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(45, 45, 45)
                .addComponent(logpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(166, 166, 166))
        );

        invoiceBigBtn.getAccessibleContext().setAccessibleName("home");

        jPanel2.setBackground(new java.awt.Color(95, 79, 205));

        jLabel2.setFont(new java.awt.Font("Curlz MT", 0, 38)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MO-SHOP");
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 51));
        jPanel2.add(jLabel2);

        jLayeredPane1.setBackground(new java.awt.Color(153, 153, 0));
        jLayeredPane1.setLayout(new java.awt.CardLayout());

        invoicePanel.setBackground(new java.awt.Color(255, 255, 255));
        invoicePanel.setToolTipText("");
        java.awt.GridBagLayout invoicePanelLayout = new java.awt.GridBagLayout();
        invoicePanelLayout.columnWidths = new int[] {0, 8, 0};
        invoicePanelLayout.rowHeights = new int[] {0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0};
        invoicePanel.setLayout(invoicePanelLayout);

        invoiceTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        invoiceTitle.setText("INVOICES");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        invoicePanel.add(invoiceTitle, gridBagConstraints);

        lblList.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblList.setText("List of Invoices");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        invoicePanel.add(lblList, gridBagConstraints);

        lblDetails.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDetails.setText("Details");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        invoicePanel.add(lblDetails, gridBagConstraints);

        tbl.setBackground(new java.awt.Color(117, 113, 220));
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl.setFillsViewportHeight(true);
        tbl.setRowHeight(25);
        jScrollPane1.setViewportView(tbl);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 5;
        invoicePanel.add(jScrollPane1, gridBagConstraints);

        SaveBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        morePanel.add(SaveBtn);

        delCheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        delCheck.setText("Delivered");
        delCheck.setToolTipText("");
        delCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delCheckActionPerformed(evt);
            }
        });
        morePanel.add(delCheck);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        invoicePanel.add(morePanel, gridBagConstraints);

        jLayeredPane1.add(invoicePanel, "card2");

        statsPanel.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.GridBagLayout statsPanelLayout = new java.awt.GridBagLayout();
        statsPanelLayout.columnWidths = new int[] {0, 0, 0, 0, 0};
        statsPanelLayout.rowHeights = new int[] {0, 7, 0, 7, 0, 7, 0};
        statsPanel.setLayout(statsPanelLayout);

        statsTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        statsTitle.setText("STATISTICS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 50, 0);
        statsPanel.add(statsTitle, gridBagConstraints);

        chartPanel.setBackground(new java.awt.Color(255, 255, 255));
        chartPanel.setMinimumSize(new java.awt.Dimension(800, 700));
        chartPanel.setPreferredSize(new java.awt.Dimension(800, 500));
        chartPanel.setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane2.setBackground(new java.awt.Color(117, 113, 220));
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setOpaque(false);
        chartPanel.add(jScrollPane2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.7;
        statsPanel.add(chartPanel, gridBagConstraints);

        btnStockIn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnStockIn.setText("Stock Insights");
        btnStockIn.setPreferredSize(new java.awt.Dimension(150, 60));
        btnStockIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStockInMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 100, 0);
        statsPanel.add(btnStockIn, gridBagConstraints);

        btnCat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCat.setText("Categories");
        btnCat.setPreferredSize(new java.awt.Dimension(150, 60));
        btnCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCatMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 100, 0);
        statsPanel.add(btnCat, gridBagConstraints);

        btnSales.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSales.setText("Sales Insights");
        btnSales.setToolTipText("");
        btnSales.setPreferredSize(new java.awt.Dimension(150, 60));
        btnSales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalesMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 100, 0);
        statsPanel.add(btnSales, gridBagConstraints);

        jLayeredPane1.add(statsPanel, "card3");

        addPanel.setBackground(new java.awt.Color(255, 255, 255));
        addPanel.setLayout(new java.awt.GridBagLayout());

        lblAddNew.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblAddNew.setText("Add New Product");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        addPanel.add(lblAddNew, gridBagConstraints);

        lblname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblname.setText("Name: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        addPanel.add(lblname, gridBagConstraints);

        txtName.setCaretColor(Color.WHITE);
        txtName.setBackground(new java.awt.Color(95, 79, 220));
        txtName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setToolTipText("");
        txtName.setMinimumSize(new java.awt.Dimension(51, 28));
        txtName.setPreferredSize(new java.awt.Dimension(200, 50));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        addPanel.add(txtName, gridBagConstraints);

        lblDesc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDesc.setText("Description:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        addPanel.add(lblDesc, gridBagConstraints);

        txtDesc.setCaretColor(Color.WHITE);
        txtDesc.setEditable(true);
        txtDesc.setBackground(new java.awt.Color(95, 79, 205));
        txtDesc.setColumns(20);
        txtDesc.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txtDesc.setForeground(new java.awt.Color(255, 255, 255));
        txtDesc.setRows(5);
        txtDesc.setPreferredSize(new java.awt.Dimension(450, 200));
        jScrollPane3.setViewportView(txtDesc);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 175;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        addPanel.add(jScrollPane3, gridBagConstraints);

        lblCat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCat.setText("Category:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        addPanel.add(lblCat, gridBagConstraints);

        txtCat.setCaretColor(Color.WHITE);
        txtCat.setBackground(new java.awt.Color(95, 79, 205));
        txtCat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCat.setForeground(new java.awt.Color(255, 255, 255));
        txtCat.setPreferredSize(new java.awt.Dimension(200, 50));
        txtCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCatActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        addPanel.add(txtCat, gridBagConstraints);

        lblBP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBP.setText("Buying Price:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        addPanel.add(lblBP, gridBagConstraints);

        txtBP.setCaretColor(Color.WHITE);
        txtBP.setBackground(new java.awt.Color(95, 79, 205));
        txtBP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtBP.setForeground(new java.awt.Color(255, 255, 255));
        txtBP.setPreferredSize(new java.awt.Dimension(200, 50));
        txtBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBPActionPerformed(evt);
            }
        });
        txtBP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBPKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        addPanel.add(txtBP, gridBagConstraints);

        lblSP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSP.setText("Selling Price:");
        lblSP.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        addPanel.add(lblSP, gridBagConstraints);

        txtSP.setCaretColor(Color.WHITE);
        txtSP.setBackground(new java.awt.Color(95, 79, 205));
        txtSP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSP.setForeground(new java.awt.Color(255, 255, 255));
        txtSP.setPreferredSize(new java.awt.Dimension(200, 50));
        txtSP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSPKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        addPanel.add(txtSP, gridBagConstraints);

        lblUrl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUrl.setText("Image URL:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        addPanel.add(lblUrl, gridBagConstraints);

        txtUrl.setCaretColor(Color.WHITE);
        txtUrl.setBackground(new java.awt.Color(95, 79, 205));
        txtUrl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtUrl.setForeground(new java.awt.Color(255, 255, 255));
        txtUrl.setPreferredSize(new java.awt.Dimension(200, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        addPanel.add(txtUrl, gridBagConstraints);

        resetBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resetBtn.setText("RESET");
        resetBtn.setPreferredSize(new java.awt.Dimension(100, 50));
        resetBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetBtnMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        addPanel.add(resetBtn, gridBagConstraints);

        addBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addBtn.setText("ADD PRODUCT");
        addBtn.setPreferredSize(new java.awt.Dimension(100, 50));
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        addPanel.add(addBtn, gridBagConstraints);

        lblQty.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblQty.setText("Quantity:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        addPanel.add(lblQty, gridBagConstraints);

        qtySpin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        qtySpin.setPreferredSize(new java.awt.Dimension(50, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        addPanel.add(qtySpin, gridBagConstraints);

        imgPreviewer.setPreferredSize(new java.awt.Dimension(400, 400));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 75, 0, 0);
        addPanel.add(imgPreviewer, gridBagConstraints);

        previewerBtn.setText("Preview Image");
        previewerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previewerBtnMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        addPanel.add(previewerBtn, gridBagConstraints);

        jLayeredPane1.add(addPanel, "card4");

        reportPanel.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.GridBagLayout reportPanelLayout = new java.awt.GridBagLayout();
        reportPanelLayout.columnWidths = new int[] {0};
        reportPanelLayout.rowHeights = new int[] {0, 7, 0, 7, 0};
        reportPanel.setLayout(reportPanelLayout);

        reportTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        reportTitle.setText("Write Your Report");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        reportPanel.add(reportTitle, gridBagConstraints);

        reportArea.setCaretColor(Color.WHITE);
        reportArea.setBackground(new java.awt.Color(95, 79, 205));
        reportArea.setColumns(20);
        reportArea.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        reportArea.setForeground(new java.awt.Color(255, 255, 255));
        reportArea.setRows(5);
        reportArea.setPreferredSize(new java.awt.Dimension(800, 800));
        jScrollPane4.setViewportView(reportArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 1000;
        gridBagConstraints.ipady = 500;
        gridBagConstraints.weightx = 0.9;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 0, 0);
        reportPanel.add(jScrollPane4, gridBagConstraints);

        saveBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        saveBtn.setText("Save Report");
        saveBtn.setPreferredSize(new java.awt.Dimension(150, 50));
        saveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveBtnMouseClicked(evt);
            }
        });
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 0, 0);
        reportPanel.add(saveBtn, gridBagConstraints);

        jLayeredPane1.add(reportPanel, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1033, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void invoiceBigBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoiceBigBtnMouseEntered
        // TODO add your handling code here:
        invoiceBigBtn.setBackground(new Color(255, 255, 255));
        lblInvoice.setForeground(new Color(95, 79, 205));
    }//GEN-LAST:event_invoiceBigBtnMouseEntered

    private void invoiceBigBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoiceBigBtnMouseExited
        // TODO add your handling code here:
        invoiceBigBtn.setBackground(new Color(156, 153, 230));
        lblInvoice.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_invoiceBigBtnMouseExited

    private void statsBigBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statsBigBtnMouseEntered
        // TODO add your handling code here:
        statsBigBtn.setBackground(new Color(255, 255, 255));
        lblStats.setForeground(new Color(95, 79, 205));
    }//GEN-LAST:event_statsBigBtnMouseEntered

    private void statsBigBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statsBigBtnMouseExited
        // TODO add your handling code here:
        statsBigBtn.setBackground(new Color(156, 153, 230));
        lblStats.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_statsBigBtnMouseExited

    private void addBigBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBigBtnMouseEntered
        // TODO add your handling code here:
        addBigBtn.setBackground(new Color(255, 255, 255));
        lblAdd.setForeground(new Color(95, 79, 205));
    }//GEN-LAST:event_addBigBtnMouseEntered

    private void addBigBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBigBtnMouseExited
        // TODO add your handling code here:
        addBigBtn.setBackground(new Color(156, 153, 230));
        lblAdd.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_addBigBtnMouseExited

    private void logpanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logpanel1MouseEntered
        // TODO add your handling code here:
        logpanel1.setBackground(new Color(255, 255, 255));
        lblLogout.setForeground(new Color(95, 79, 205));
    }//GEN-LAST:event_logpanel1MouseEntered

    private void logpanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logpanel1MouseExited
        // TODO add your handling code here:
        logpanel1.setBackground(new Color(156, 153, 230));
        lblLogout.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_logpanel1MouseExited

    private void invoiceBigBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoiceBigBtnMouseClicked
        // TODO add your handling code here:
        jLayeredPane1.removeAll();
        jLayeredPane1.add(invoicePanel);
        jLayeredPane1.repaint();
        jLayeredPane1.validate();

    }//GEN-LAST:event_invoiceBigBtnMouseClicked

    private void statsBigBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statsBigBtnMouseClicked
        // TODO add your handling code here:
        jLayeredPane1.removeAll();
        jLayeredPane1.add(statsPanel);
        jLayeredPane1.repaint();
        jLayeredPane1.validate();
    }//GEN-LAST:event_statsBigBtnMouseClicked

    private void delCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delCheckActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:

        if (tbl.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Select An Invoice First !");

        } else {
            //getting value of invoice id
            int myId = (int) tbl.getValueAt(0, 0);

            //getting value of delivered column
            boolean alreadyDel = (boolean) tbl.getValueAt(0, 5);

            //checking if delivered and if checkbox is checked
            if (delCheck.isSelected() && !alreadyDel) {
                String query = "UPDATE invoice SET delivered = 1 where id =? ";
                PreparedStatement stm;

                try {
                    stm = conn.prepareStatement(query);
                    stm.setInt(1, myId);
                    stm.execute();
                    JOptionPane.showMessageDialog(null, "Delivery Completed !");

                } catch (SQLException ex) {
                    Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (alreadyDel) {
                JOptionPane.showMessageDialog(null, "Already Delivered !!!");
            } else {
                JOptionPane.showMessageDialog(null, "Please check the box !");
            }

        }
        //reset checkbox
        delCheck.setSelected(false);
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void reportBigBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportBigBtnMouseExited
        // TODO add your handling code here:
        reportBigBtn.setBackground(new Color(117, 113, 220));
        lblReport.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_reportBigBtnMouseExited

    private void reportBigBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportBigBtnMouseEntered
        // TODO add your handling code here:
        reportBigBtn.setBackground(new Color(255, 255, 255));
        lblReport.setForeground(new Color(95, 79, 205));
    }//GEN-LAST:event_reportBigBtnMouseEntered

    private void addBigBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBigBtnMouseClicked
        // TODO add your handling code here:
        jLayeredPane1.removeAll();
        jLayeredPane1.add(addPanel);
        jLayeredPane1.repaint();
        jLayeredPane1.validate();


    }//GEN-LAST:event_addBigBtnMouseClicked

    private void reportBigBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportBigBtnMouseClicked
        // TODO add your handling code here:
        jLayeredPane1.removeAll();
        jLayeredPane1.add(reportPanel);
        jLayeredPane1.repaint();
        jLayeredPane1.validate();
    }//GEN-LAST:event_reportBigBtnMouseClicked

    private void btnSalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalesMouseClicked
        try {
            //set according to session
            //int wholesalerid = 3;
            ResultSet rs;
            String query = "SELECT COUNT(*), date_added FROM purchases WHERE wholesaler_id = ? GROUP BY date_added";

            PreparedStatement stm = conn.prepareStatement(query);
            stm.setInt(1, wholesalerid);
            rs = stm.executeQuery();

            DefaultCategoryDataset dataset = new DefaultCategoryDataset();
            while (rs.next()) {
                int count = rs.getInt("COUNT(*)");
                Date d = rs.getDate("date_added");
                //System.out.println(count);
                //System.out.println(d);
                dataset.addValue(count, "Sales", d);
            }
            JFreeChart graph = ChartFactory.createLineChart("Sales Per Day", "Days", "Sales", dataset, PlotOrientation.VERTICAL, true, true, false);
            ChartPanel p = new ChartPanel(graph);

            //set background to color required
            Plot plot = graph.getPlot();
            plot.setBackgroundPaint(new Color(204, 204, 255));

            chartPanel.removeAll();
            chartPanel.add(p);

            chartPanel.validate();

        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnSalesMouseClicked

    private void btnCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCatMouseClicked
        try {
            // TODO add your handling code here:
            String query = "SELECT COUNT(*), category.name FROM stock, product, category WHERE stock.wholesaler_id = ? AND stock.product_id = product.id AND product.category_id = category.id GROUP BY category.name";
            //set session id
            //int wholesalerid = 3;
            ResultSet rs;

            PreparedStatement stm = conn.prepareStatement(query);
            stm.setInt(1, wholesalerid);
            rs = stm.executeQuery();

            DefaultPieDataset dataset = new DefaultPieDataset();

            while (rs.next()) {
                String cat = rs.getString("name");
                int co = rs.getInt("COUNT(*)");
                /*
                System.out.println(cat);
                System.out.println(co);
                 */

                dataset.setValue(cat, co);
            }
            JFreeChart piechart = ChartFactory.createPieChart("Product Categories", dataset, true, true, false);
            ChartPanel pie = new ChartPanel(piechart);

            //set background to color required
            Plot plot = piechart.getPlot();
            plot.setBackgroundPaint(new Color(204, 204, 255));

            chartPanel.removeAll();
            chartPanel.add(pie);
            chartPanel.validate();

        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCatMouseClicked

    private void btnStockInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStockInMouseClicked
        try {
            // TODO add your handling code here:

            //replace with login session id
            //int wholesalerid = 3;
            String query = "SELECT stock.quantityInStock, product.name FROM stock, product WHERE stock.product_id = product.id AND stock.wholesaler_id = ?";
            PreparedStatement stm = conn.prepareStatement(query);
            stm.setInt(1, wholesalerid);
            ResultSet rs = stm.executeQuery();

            DefaultCategoryDataset dataset = new DefaultCategoryDataset();

            while (rs.next()) {

                int qty = rs.getInt("quantityInStock");
                String pname = rs.getString("name");
                dataset.addValue(qty, "Quantity", pname);

            }

            //dataset.addValue(1.0,"TEst","10");
            JFreeChart barChart = ChartFactory.createBarChart("Stock", "Product", "Quantity in Stock", dataset, PlotOrientation.VERTICAL, true, true, false);
            ChartPanel x = new ChartPanel(barChart);
            x.setPreferredSize(new Dimension(500, 500));

            //set background to color required
            Plot plot = barChart.getPlot();
            plot.setBackgroundPaint(new Color(204, 204, 255));

            chartPanel.removeAll();
            chartPanel.add(x);
            chartPanel.validate();
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnStockInMouseClicked

    private void txtBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBPActionPerformed

    private void txtCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCatActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    public void numValidate(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (Character.isLetter(c) && !evt.isAltDown()) {
            evt.consume();
            getToolkit().beep();
        }
    }
    private void txtBPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBPKeyTyped
        // TODO add your handling code here:
        numValidate(evt);
    }//GEN-LAST:event_txtBPKeyTyped

    private void txtSPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSPKeyTyped
        // TODO add your handling code here:
        numValidate(evt);
    }//GEN-LAST:event_txtSPKeyTyped

    private void resetBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetBtnMouseClicked
        // TODO add your handling code here:
        txtName.setText("");
        txtDesc.setText("");
        txtCat.setText("");
        txtBP.setText("");
        txtSP.setText("");
        txtUrl.setText("");
        qtySpin.setValue(0);
    }//GEN-LAST:event_resetBtnMouseClicked

    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked
        // TODO add your handling code here:

        //set session id
        //int wholesalerid = 3;
        String name = txtName.getText();
        String desc = txtDesc.getText();
        String cat = txtCat.getText();
        String url = txtUrl.getText();
        String sbp = txtBP.getText();
        String ssp = txtSP.getText();
        int qty = (int) qtySpin.getValue();

        if (name.isEmpty() || desc.isEmpty() || cat.isEmpty() || url.isEmpty() || sbp.isEmpty() || ssp.isEmpty() || qty == 0) {
            JOptionPane.showMessageDialog(null, "Fill all fields");

            name = txtName.getText();
            desc = txtDesc.getText();
            cat = txtCat.getText();
            url = txtUrl.getText();
            sbp = txtBP.getText();
            ssp = txtSP.getText();
        } else {
            double bp = Double.parseDouble(sbp);
            double sp = Double.parseDouble(ssp);

            //Check for category
            int catid = 0;
            String query = "SELECT id, name FROM category";
            ResultSet rs;
            try {
                Statement s = conn.createStatement();
                rs = s.executeQuery(query);
                while (rs.next()) {
                    if (rs.getString("name").toLowerCase().equals(cat.trim().toLowerCase())) {
                        catid = rs.getInt("id");
                        System.out.println(catid);
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (catid == 0) {
                //create a category
                String dbin = "INSERT INTO category(name) VALUES (?)";
                try {
                    PreparedStatement st = conn.prepareStatement(dbin);
                    st.setString(1, cat);
                    st.executeUpdate();

                    String idquery = "SELECT id FROM category WHERE name = ?";
                    PreparedStatement idStm = conn.prepareStatement(idquery);
                    idStm.setString(1, cat.trim());
                    ResultSet ids = idStm.executeQuery();

                    while (ids.next()) {
                        catid = ids.getInt("id");
                        System.out.println(catid);
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
            Product p = new Product(name, desc, catid, url, bp, sp);

            String pQuery = "INSERT INTO product(name,description,category_id,image_url,buy_price,sell_price) VALUES (?,?,?,?,?,?)";
            try {
                //inserting product into db
                PreparedStatement qstm = conn.prepareStatement(pQuery);
                qstm.setString(1, p.getName());
                qstm.setString(2, p.getDescription());
                qstm.setInt(3, p.getCategory_id());
                qstm.setString(4, p.getImage_url());
                qstm.setDouble(5, p.getBuy_price());
                qstm.setDouble(6, p.getSell_price());
                qstm.executeUpdate();

                //getting id of product created
                String pid = "SELECT id FROM product WHERE name = ?";
                PreparedStatement pstm = conn.prepareStatement(pid);
                pstm.setString(1, p.getName());
                ResultSet valID = pstm.executeQuery();
                while (valID.next()) {
                    //setting value of id returned to p object
                    p.setId(valID.getInt("id"));
                }
                //push values in stock table
                String stkIns = "INSERT INTO stock VALUES(?,?,?)";
                PreparedStatement stkStm = conn.prepareStatement(stkIns);
                stkStm.setInt(1, wholesalerid);
                stkStm.setInt(2, p.getId());
                stkStm.setInt(3, qty);
                stkStm.executeUpdate();

                JOptionPane.showMessageDialog(null, "Product Added !");

            } catch (SQLException ex) {
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_addBtnMouseClicked

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveBtnActionPerformed

    private void saveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtnMouseClicked
        // TODO add your handling code here:
        JFileChooser filepicker = new JFileChooser();
        filepicker.showSaveDialog(this);

        File f = filepicker.getSelectedFile();

        try {
            FileWriter fw = new FileWriter(f);
            String reportText = reportArea.getText();
            fw.write(reportText);
            fw.close();

        } catch (IOException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_saveBtnMouseClicked

    private void logpanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logpanel1MouseClicked
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "Are You Sure ?", "Logout", JOptionPane.YES_NO_OPTION);

        if (response == JOptionPane.YES_OPTION) {
            setVisible(false);
            //new LoginForm().setVisible(true);
        }
    }//GEN-LAST:event_logpanel1MouseClicked

    private void previewerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previewerBtnMouseClicked
        // TODO add your handling code here:
        imgPreviewer.removeAll();
        String picUrl = txtUrl.getText();
        if (picUrl.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insert Url");
        } else {

            Image image = null;
            try {
                URL url = new URL(picUrl);
                image = new ImageIcon(ImageIO.read(url)).getImage().getScaledInstance(400, 400, Image.SCALE_DEFAULT);
                JLabel imgicon = new JLabel(new ImageIcon(image));
                imgPreviewer.add(imgicon);

            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Re enter Url");
                txtUrl.setText("");
            }
        }


    }//GEN-LAST:event_previewerBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard(3).setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveBtn;
    private javax.swing.JPanel addBigBtn;
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel addIco;
    private javax.swing.JPanel addPanel;
    private javax.swing.JButton btnCat;
    private javax.swing.JButton btnSales;
    private javax.swing.JButton btnStockIn;
    private javax.swing.JPanel chartPanel;
    private javax.swing.JCheckBox delCheck;
    private javax.swing.JPanel imgPreviewer;
    private javax.swing.JPanel invoiceBigBtn;
    private javax.swing.JLabel invoiceIco;
    private javax.swing.JPanel invoicePanel;
    private javax.swing.JLabel invoiceTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblAddNew;
    private javax.swing.JLabel lblBP;
    private javax.swing.JLabel lblCat;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblDetails;
    private javax.swing.JLabel lblInvoice;
    private javax.swing.JLabel lblList;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblReport;
    private javax.swing.JLabel lblSP;
    private javax.swing.JLabel lblStats;
    private javax.swing.JLabel lblUrl;
    private javax.swing.JLabel lblname;
    private javax.swing.JPanel logpanel1;
    private javax.swing.JPanel morePanel;
    private javax.swing.JLabel outIco;
    private javax.swing.JButton previewerBtn;
    private javax.swing.JSpinner qtySpin;
    private javax.swing.JTextArea reportArea;
    private javax.swing.JPanel reportBigBtn;
    private javax.swing.JLabel reportIco;
    private javax.swing.JPanel reportPanel;
    private javax.swing.JLabel reportTitle;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JPanel statsBigBtn;
    private javax.swing.JLabel statsIco;
    private javax.swing.JPanel statsPanel;
    private javax.swing.JLabel statsTitle;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtBP;
    private javax.swing.JTextField txtCat;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSP;
    private javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables
}
